name: Model Validate and Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-and-build:
    uses: CBIIT/bento-workflows/.github/workflows/model-test-and-deploy.yml@v1.1.3.1
    with:
      model_files: |
        ctdc_model_file.yaml ctdc_model_properties_file.yaml
      model_prefix: ctdc-model
      event_name: ${{ github.event_name }}
    secrets:
      docker_repo: ${{ secrets.REPO }}
      docker_svc: ${{ secrets.RSVC }}
      repo_user: ${{ secrets.REPO_USER }}
      repo_pw: ${{ secrets.REPO_PW }}
